### ISSUE TITLE
请问怎么自定义配置呢？有些网站不想让他走代理，有方法实现吗？

### ISSUE THREAD

**Issue by NOWorEVER** [haishanh/yacd#661]
请问怎么自定义配置呢？有些网站不想让他走代理，有方法实现吗？

**Comment by JohanChane** [comment]
[clash rules](https://github.com/Loyalsoldier/clash-rules#%E7%99%BD%E5%90%8D%E5%8D%95%E6%A8%A1%E5%BC%8F-rules-%E9%85%8D%E7%BD%AE%E6%96%B9%E5%BC%8F%E6%8E%A8%E8%8D%90)

[rule behavior](https://github.com/Dreamacro/clash/wiki/premium-core-features#domain)

我的规则

> 用法：遇到不常用的网站，将 RuleMode（默认是第一个）调到 PROXY, 访问完之后调回。

```yaml
proxy-groups:
  - name: "PROXY"
    type: select
    # disable-udp: true
    proxies:
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 300

  - name: "RuleMode"
    type: select
    # disable-udp: true
    proxies:
      - DIRECT
      - PROXY

rules:
  # # # 黑名单模式（只有命中规则的网络流量，才使用代理）
  # # ## Custom
  # # ## No Custom
  # - RULE-SET,applications,DIRECT
  #
  # - DOMAIN,clash.razord.top,DIRECT
  # - DOMAIN,yacd.haishan.me,DIRECT
  #
  # - RULE-SET,private,DIRECT
  # - RULE-SET,reject,REJECT
  # - RULE-SET,tld-not-cn,PROXY
  # - RULE-SET,gfw,PROXY
  # - RULE-SET,greatfire,PROXY
  # - RULE-SET,telegramcidr,PROXY
  #
  # # ## 黑名单模式
  # - MATCH,DIRECT

  # # # 白名单模式（没有命中规则的网络流量，统统使用代理）
  # # ## Custom
  # # ## No Custom
  # - RULE-SET,applications,DIRECT
  #
  # - DOMAIN,clash.razord.top,DIRECT
  # - DOMAIN,yacd.haishan.me,DIRECT
  #
  # - RULE-SET,private,DIRECT
  # - RULE-SET,reject,REJECT
  # - RULE-SET,icloud,DIRECT
  # - RULE-SET,apple,DIRECT
  # - RULE-SET,google,DIRECT
  # - RULE-SET,proxy,PROXY
  # - RULE-SET,direct,DIRECT
  # - RULE-SET,lancidr,DIRECT
  # - RULE-SET,cncidr,DIRECT
  # - RULE-SET,telegramcidr,PROXY
  #
  # - GEOIP,,DIRECT
  # - GEOIP,CN,DIRECT
  #
  # # ## 白名单模式
  # - MATCH,PROXY

  # # My Mode
  # ## Custom
  # ### App
  # - PROCESS-NAME,v2ray,DIRECT
  # - PROCESS-NAME,v2ray.exe,DIRECT
  # ### Domain
  - DOMAIN,raw.githubusercontent.com,PROXY
  # #### Basic
  - DOMAIN-SUFFIX,hcaptcha.com,PROXY
  - DOMAIN-SUFFIX,captcha.website,PROXY

  # #### Common
  - DOMAIN-SUFFIX,v2rayse.com,PROXY
  - DOMAIN-SUFFIX,bianyuan.xyz,PROXY

  # ## No Custom
  - RULE-SET,applications,DIRECT

  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT

  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY

  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT

  - GEOIP,,DIRECT
  - GEOIP,CN,DIRECT

  - MATCH,RuleMode
```
