### ISSUE TITLE
同一局域网机器上设置external-controller后依然failed to connect

### ISSUE THREAD

**Issue by LittleYe233** [haishanh/yacd#662]
同一局域网下另一主机（Arch Linux ARM）上 config.yml 的相关配置如下：

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
```

命令行参数是： `clash -f config.yml`。在本机浏览器访问 http://192.168.0.x:9090 能得到正确 response，但使用 yacd 显示 failed to connect。
