### ISSUE TITLE
How to select the proxy in proxy-group of fallback type

### ISSUE THREAD

**Issue by JohanChane** [haishanh/yacd#712]
for example

```yaml
proxy-groups:
  - name: "AllFallback"
    type: fallback
    use:
    proxies:
      - NodeAuto
      - AuxiliaryAuto
    url: 'https://www.google.com'
    interval: 30
```

Sometime the selected proxy is AuxiliaryAuto, however I want to select the NodeAuto.
