### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by rebootbot** [haishanh/yacd#837]
，

**Comment by acmookey** [comment]
你可以把管理页面端口也设置成9090。然后通过单独的frpc服务来配置内网穿透

- OpenClash配置页面
![image](https://github.com/haishanh/yacd/assets/6263624/621a3d0a-3e62-4ad1-a913-5b3c480ad9ee)

- frpc.toml
```toml
[[proxies]]
name      = "yacd"
type      = "http"
localPort = 9090
customDomains = ["yacd.test.com"]
```
